n_layers: 4
n_blocks: 3

net:
    conv_first:
        - {type: "conv", x_size: 3, y_size: 3, x_stride: 1, y_stride: 1, n_filter: 64, activation: "leaky_relu", name: "conv1", bn: True}
    
    conv_layer1:
        - {type: "conv", x_size: 3, y_size: 3, x_stride: 1, y_stride: 1, n_filter: 64, activation: "leaky_relu", name: "conv2", bn: True}
        - {type: "conv", x_size: 3, y_size: 3, x_stride: 1, y_stride: 1, n_filter: 64, activation: "none", name: "conv3", bn: True}
        - {type: "conv", x_size: 3, y_size: 3, x_stride: 1, y_stride: 1, n_filter: 64, activation: "leaky_relu", name: "conv4", bn: True}
        - {type: "conv", x_size: 3, y_size: 3, x_stride: 1, y_stride: 1, n_filter: 64, activation: "none", name: "conv5", bn: True}
        - {type: "conv", x_size: 3, y_size: 3, x_stride: 1, y_stride: 1, n_filter: 64, activation: "leaky_relu", name: "conv6", bn: True}
        - {type: "conv", x_size: 3, y_size: 3, x_stride: 1, y_stride: 1, n_filter: 64, activation: "none", name: "conv7", bn: True}
        
    conv_layer2:
        - {type: "conv", x_size: 3, y_size: 3, x_stride: 2, y_stride: 2, n_filter: 128, activation: "leaky_relu", name: "conv8", bn: True}
        - {type: "conv", x_size: 3, y_size: 3, x_stride: 1, y_stride: 1, n_filter: 128, activation: "none", name: "conv9", bn: True}
        
        - {type: "conv", x_size: 3, y_size: 3, x_stride: 1, y_stride: 1, n_filter: 128, activation: "leaky_relu", name: "conv10", bn: True}
        - {type: "conv", x_size: 3, y_size: 3, x_stride: 1, y_stride: 1, n_filter: 128, activation: "none", name: "conv11", bn: True}
        - {type: "conv", x_size: 3, y_size: 3, x_stride: 1, y_stride: 1, n_filter: 128, activation: "leaky_relu", name: "conv12", bn: True}
        - {type: "conv", x_size: 3, y_size: 3, x_stride: 1, y_stride: 1, n_filter: 128, activation: "none", name: "conv13", bn: True}
        - {type: "conv", x_size: 3, y_size: 3, x_stride: 1, y_stride: 1, n_filter: 128, activation: "leaky_relu", name: "conv14", bn: True}
        - {type: "conv", x_size: 3, y_size: 3, x_stride: 1, y_stride: 1, n_filter: 128, activation: "none", name: "conv15", bn: True}
        
    conv_layer3:
        - {type: "conv", x_size: 3, y_size: 3, x_stride: 2, y_stride: 2, n_filter: 256, activation: "leaky_relu", name: "conv16", bn: True}
        - {type: "conv", x_size: 3, y_size: 3, x_stride: 1, y_stride: 1, n_filter: 256, activation: "none", name: "conv17", bn: True}
        
        - {type: "conv", x_size: 3, y_size: 3, x_stride: 1, y_stride: 1, n_filter: 256, activation: "leaky_relu", name: "conv18", bn: True}
        - {type: "conv", x_size: 3, y_size: 3, x_stride: 1, y_stride: 1, n_filter: 256, activation: "none", name: "conv19", bn: True}
        - {type: "conv", x_size: 3, y_size: 3, x_stride: 1, y_stride: 1, n_filter: 256, activation: "leaky_relu", name: "conv20", bn: True}
        - {type: "conv", x_size: 3, y_size: 3, x_stride: 1, y_stride: 1, n_filter: 256, activation: "none", name: "conv21", bn: True}
        - {type: "conv", x_size: 3, y_size: 3, x_stride: 1, y_stride: 1, n_filter: 256, activation: "leaky_relu", name: "conv22", bn: True}
        - {type: "conv", x_size: 3, y_size: 3, x_stride: 1, y_stride: 1, n_filter: 256, activation: "none", name: "conv23", bn: True}
        
    conv_layer4:
        - {type: "conv", x_size: 3, y_size: 3, x_stride: 2, y_stride: 2, n_filter: 512, activation: "leaky_relu", name: "conv24", bn: True}
        - {type: "conv", x_size: 3, y_size: 3, x_stride: 1, y_stride: 1, n_filter: 512, activation: "none", name: "conv25", bn: True}
        
        - {type: "conv", x_size: 3, y_size: 3, x_stride: 1, y_stride: 1, n_filter: 512, activation: "leaky_relu", name: "conv26", bn: True}
        - {type: "conv", x_size: 3, y_size: 3, x_stride: 1, y_stride: 1, n_filter: 512, activation: "none", name: "conv27", bn: True}
        - {type: "conv", x_size: 3, y_size: 3, x_stride: 1, y_stride: 1, n_filter: 512, activation: "leaky_relu", name: "conv28", bn: True}
        - {type: "conv", x_size: 3, y_size: 3, x_stride: 1, y_stride: 1, n_filter: 512, activation: "none", name: "conv29", bn: True}
        - {type: "conv", x_size: 3, y_size: 3, x_stride: 1, y_stride: 1, n_filter: 512, activation: "leaky_relu", name: "conv30", bn: True}
        - {type: "conv", x_size: 3, y_size: 3, x_stride: 1, y_stride: 1, n_filter: 512, activation: "none", name: "conv31", bn: True}
    
    dense_first:
        - {type: "dense", hidden_dim: 2048, dropout: True, activation: "leaky_relu", name: "dense1", bn: True}
    
    dense:
        - {type: "dense", hidden_dim: 10, dropout: False, activation: "none", name: "dense2", bn: False}
